# Generated by Django 2.0.2 on 2022-05-12 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20220513_0037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='summery',
            new_name='summary',
        ),
    ]
