# Generated by Django 2.0.2 on 2022-05-12 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20220513_0125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='imagefull',
            new_name='image',
        ),
    ]
